# Generated by Django 4.2.7 on 2023-11-25 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('codigo_emp', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('ruc', models.CharField(max_length=11)),
                ('correo', models.EmailField(max_length=254)),
                ('contrasena', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('codigo_usu', models.AutoField(primary_key=True, serialize=False)),
                ('provider_id', models.CharField(max_length=255)),
                ('provider_specific_uid', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=200)),
                ('dni', models.CharField(max_length=8)),
                ('correo', models.EmailField(max_length=254)),
                ('contrasena', models.CharField(max_length=20)),
                ('photo_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('codigo_rep', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usu', models.CharField(max_length=200)),
                ('tipo_rep', models.CharField(choices=[('Reporte de Luz', 'Reporte de Luz'), ('Reporte de Agua', 'Reporte de Agua'), ('Reporte de Calidad de Aire', 'Reporte de Calidad de Aire'), ('Reporte de Movimiento', 'Reporte de Movimiento')], max_length=30)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=250)),
                ('codigo_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.empresa')),
                ('codigo_usu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='codigo_usu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usuario'),
        ),
    ]
