# Generated by Django 4.2.8 on 2023-12-19 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('codigo_emp', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(default='', max_length=20)),
                ('nombre_o_razon_social', models.CharField(default='', max_length=255)),
                ('tipo_contribuyente', models.CharField(default='', max_length=50)),
                ('estado', models.CharField(default='', max_length=20)),
                ('condicion', models.CharField(default='', max_length=20)),
                ('departamento', models.CharField(default='', max_length=50)),
                ('provincia', models.CharField(default='', max_length=50)),
                ('distrito', models.CharField(default='', max_length=50)),
                ('direccion', models.CharField(default='', max_length=255)),
                ('direccion_completa', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('provider_id', models.CharField(max_length=255)),
                ('provider_specific_uid', models.CharField(max_length=255)),
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('dni', models.CharField(max_length=8)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('photo_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('codigo_rep', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usu', models.CharField(max_length=200)),
                ('tipo_rep', models.CharField(choices=[('Reporte de Luz', 'Reporte de Luz'), ('Reporte de Agua', 'Reporte de Agua'), ('Reporte de Calidad de Aire', 'Reporte de Calidad de Aire'), ('Reporte de Movimiento', 'Reporte de Movimiento')], max_length=30)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=250)),
                ('codigo_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.empresa')),
                ('codigo_usu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='codigo_usu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usuario'),
        ),
    ]
