# Generated by Django 4.2.7 on 2023-11-10 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('codigo_rep', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usu', models.CharField(max_length=200)),
                ('tipo_rep', models.CharField(choices=[('Reporte de Luz', 'Reporte de Luz'), ('Reporte de Agua', 'Reporte de Agua'), ('Reporte de Calidad de Aire', 'Reporte de Calidad de Aire'), ('Reporte de Movimiento', 'Reporte de Movimiento')], max_length=30)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=250)),
                ('codigo_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.empresa')),
                ('codigo_usu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usuario')),
            ],
        ),
    ]
