# Generated by Django 4.2.8 on 2023-12-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usuario_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(default='', max_length=200),
        ),
    ]
