# Generated by Django 4.2.8 on 2023-12-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usuario_apellidos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='contrasena',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='ruc',
        ),
        migrations.AddField(
            model_name='empresa',
            name='condicion',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='empresa',
            name='departamento',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='empresa',
            name='direccion',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='empresa',
            name='direccion_completa',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='empresa',
            name='distrito',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='empresa',
            name='estado',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nombre_o_razon_social',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='empresa',
            name='numero',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='empresa',
            name='provincia',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tipo_contribuyente',
            field=models.CharField(default='', max_length=50),
        ),
    ]
