# Generated by Django 4.2.8 on 2023-12-19 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_usuario_username_alter_usuario_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='nombre',
            new_name='nombres',
        ),
    ]
