# Generated by Django 4.2.8 on 2023-12-19 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_usuario_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
    ]
