# Generated by Django 4.2.7 on 2023-11-09 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('cod_modulo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(max_length=20)),
                ('codigo_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Temporizadores',
            fields=[
                ('cod_temp', models.AutoField(primary_key=True, serialize=False)),
                ('temp_inicio', models.DateTimeField()),
                ('temp_fin', models.DateTimeField()),
                ('accion', models.CharField(max_length=25)),
                ('codigo_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrosUltrasonico',
            fields=[
                ('cod_registro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('distancia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidadmedida', models.CharField(max_length=255)),
                ('detecmov', models.BooleanField()),
                ('cod_modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.modulo')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrosRele',
            fields=[
                ('cod_registro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('accion', models.CharField(max_length=25)),
                ('cod_modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.modulo')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrosAire',
            fields=[
                ('cod_registro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('calidad_aire', models.CharField(max_length=255)),
                ('monoxcarbono', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amoniaco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('alerta', models.CharField(max_length=255)),
                ('dlargo_plazo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cont_ventilacion', models.BooleanField()),
                ('cot_purificado', models.BooleanField()),
                ('cod_modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.modulo')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrosAgua',
            fields=[
                ('cod_registro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('flujo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidadmedida', models.CharField(max_length=5)),
                ('nivelflujo', models.CharField(max_length=25)),
                ('cod_modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.modulo')),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimientos',
            fields=[
                ('cod_mant', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('tipo_mant', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('realizado', models.BooleanField()),
                ('codigo_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='AlertasSonico',
            fields=[
                ('cod_alerta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('tipo_alerta', models.CharField(max_length=255)),
                ('cod_modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.modulo')),
                ('cod_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.registrosultrasonico')),
            ],
        ),
        migrations.CreateModel(
            name='AlertasRele',
            fields=[
                ('cod_alerta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('tipo_alerta', models.CharField(max_length=255)),
                ('cod_modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.modulo')),
                ('cod_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.registrosrele')),
            ],
        ),
        migrations.CreateModel(
            name='AlertasAire',
            fields=[
                ('cod_alerta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('tipo_alerta', models.CharField(max_length=255)),
                ('cod_modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.modulo')),
                ('cod_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.registrosaire')),
            ],
        ),
        migrations.CreateModel(
            name='AlertasAgua',
            fields=[
                ('cod_alerta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('tipo_alerta', models.CharField(max_length=255)),
                ('cod_modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.modulo')),
                ('cod_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.registrosagua')),
            ],
        ),
    ]
