# Generated by Django 4.2.7 on 2023-11-25 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_dispositivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('state', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Dispositivo',
        ),
    ]
