# Generated by Django 4.2.7 on 2023-12-14 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usuario_telefono'),
        ('iot', '0004_rele_delete_relay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertassonico',
            name='cod_modulo',
        ),
        migrations.RemoveField(
            model_name='alertassonico',
            name='cod_registro',
        ),
        migrations.RemoveField(
            model_name='modulo',
            name='codigo_emp',
        ),
        migrations.RemoveField(
            model_name='temporizadores',
            name='codigo_emp',
        ),
        migrations.AddField(
            model_name='modulo',
            name='codigo_usu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.usuario'),
        ),
        migrations.AddField(
            model_name='temporizadores',
            name='codigo_usu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.usuario'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='temporizadores',
            name='accion',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='AlertasAgua',
        ),
        migrations.DeleteModel(
            name='AlertasSonico',
        ),
    ]
