# Generated by Django 4.2.7 on 2023-12-14 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usuario_telefono'),
        ('iot', '0005_remove_alertassonico_cod_modulo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporizadores',
            name='codigo_emp',
        ),
        migrations.AddField(
            model_name='temporizadores',
            name='codigo_usu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.usuario'),
        ),
    ]
